version: 0.2

env:
 variables:
  env: "dev"
  dept: "ps"

phases:
 install:
  commands:
   - printenv
 pre_build:
  commands:
   - echo "exit 0" >> test.sh
   - chmod +X test.sh
 build:
  commands:
   - bash test.sh
 post_build:
  commands:
   - echo "Nothing to do here @ post_build"

artifacts:
 files:
  - application.py
